name: CI

on:
 
  push:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GINGER_API_KEY: ${{ secrets.GINGER_API_KEY }} 
      PUBLIC_API_URL: https://api.online.emspay.eu
      ORDER_ID_FOR_TESTS: 06a2cf1d-570d-4461-b8c2-42fc45d18dab
  

    steps:
      - uses: actions/checkout@v2
      - name: Install dependecies
        run: composer install
      - name: Run all tests
        run: vendor/bin/phpunit src/Tests
