name: CI

on:
 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - name: Install dependecies
        run: composer install
      - name: Run all tests
        run: vendor/bin/phpunit src/tests
