name: CI

on:
 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GINGER_API_KEY: ${{ secrets.GINGER_API_KEY }} 

    steps:
      - uses: actions/checkout@v2
      - name: Install dependecies
        run: composer install
      - name: set .env vars
        run: |
          sudo find -name '.env' -exec sed -i 's%PUBLIC_API_URL=%PUBLIC_API_URL=https://api.online.emspay.eu%' {} +
          sudo find -name '.env' -exec sed -i 's%ORDER_ID_FOR_TESTS=%ORDER_ID_FOR_TESTS=e5a82e76-5269-4401-9ae9-9239bdf22176%' {} +
      - name: Run all tests
        run: vendor/bin/phpunit src/Tests
