name: CI

on:
 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GINGER_API_KEY: ${{ secrets.GINGER_API_KEY }} 
  

    steps:
      - uses: actions/checkout@v2
      - name: Install dependecies
        run: composer install
      - name: Add API-Key to ENV
        run: ${{ env.GINGER_API_KEY = secrets.GINGER_API_KEY }} 
        
      - name: Run all tests
        run: vendor/bin/phpunit src/Tests
